[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "distributed_learning_simulation"
version = "0.2"
requires-python = ">=3.11"
readme = {file = "README.md", content-type = "text/markdown"}
authors = [
  {name = "cyy", email = "cyyever@outlook.com"},
]
license = {text = "BSD License"}
classifiers = [
  "Programming Language :: Python"
]


[project.urls]
Repository = "https://github.com/cyyever/distributed_learning_simulation_lib"

[tool.pyright]
include = ["simulation_lib"]
defineConstant = { DEBUG = true }

reportMissingImports = true
reportMissingTypeStubs = false
